export { Header } from 'components/Header'
export { Home } from 'components/Home'
export { Main } from 'components/Main'
export { Podcast } from 'components/Podcast'
export { Contact } from 'components/Contact'
export { Inscription } from 'component/Inscription'